[package]
name = "derivative"
version = "1.0.0"
authors = ["mcarton <cartonmartin+git@gmail.com>"]
license = "MIT/Apache-2.0"
documentation = "https://mcarton.github.io/rust-derivative/"
repository = "https://github.com/mcarton/rust-derivative"
description = "A set of alternative `derive` attributes for Rust"
keywords = ["derive", "macro", "macro1-1", "plugin"]
categories = ["rust-patterns"]

[badges]
travis-ci = { repository = "mcarton/rust-derivative" }
appveyor = { repository = "mcarton/rust-derivative" }

[lib]
proc-macro = true

[dependencies]
quote = "0.5"
syn = { version = "0.13", features = ["extra-traits", "full", "visit"] }
compiletest_rs = { version = "0.3", optional = true }

[features]
nightly = ["compiletest_rs"]
